### ISSUE TITLE
Get youtube autogenerated playlist

### ISSUE THREAD

**Issue by roiniti** [twlite/youtube-sr#31]
It's posible to get the content of a youtube autogenerated playlist like this:
**https://www.youtube.com/watch?v=zhl-Cs1-sG4&list=RDzhl-Cs1-sG4** 
I get Error: Invalid playlist url and when the url is valid, like this:
**https://www.youtube.com/watch?v=FGBhQbmPwH8&list=RDEMni3jl65KF37F9JYsJM8DGg**
 the getPlaylist method returns null.
I'm using the wrong method or it's not implemented? If its not implemented its possible to implement it?

**Comment by DevAndromeda** [comment]
> It's posible to get the content of a youtube autogenerated playlist like this:
https://www.youtube.com/watch?v=zhl-Cs1-sG4&list=RDzhl-Cs1-sG4

no this is not yet supported.

> https://www.youtube.com/watch?v=FGBhQbmPwH8&list=RDEMni3jl65KF37F9JYsJM8DGg
the getPlaylist method returns null.

if the url includes `/watch?v=`, it is considered as a video, not playlist.

**Comment by roiniti** [comment]
The watch?v= its for the first video i think. This playlist: 
**https://www.youtube.com/watch?v=LrHLJwV6Sio&list=PL5rpAdmuJ-hFbOgszRCsgeO-fBwGz8dTL**
(not autogenerated) also contains the watch?v= but it works fine in youtube-sr

**Comment by DevAndromeda** [comment]
> The watch?v= its for the first video i think. This playlist:
https://www.youtube.com/watch?v=LrHLJwV6Sio&list=PL5rpAdmuJ-hFbOgszRCsgeO-fBwGz8dTL
(not autogenerated) also contains the watch?v= but it works fine in youtube-sr

Looks like that playlist had some errors while parsing due to which it returned `null` before. I will look into it in few days ✌️

> And you plan to add support to the youtube autogenerated playlists?

yes, I will try to do it in few days 😄

**Comment by Shiny1708** [comment]
Any updates on this?
