### ISSUE TITLE
Error: Could not parse video metadata!

### ISSUE THREAD

**Issue by lihuelworks** [twlite/youtube-sr#63]
Been having this error with long playlists (+1k). 

Error: Could not parse video metadata!
    at Util.getVideo (C:\Users\yerba\Documents\code\youtube_sr_test\node_modules\.pnpm\youtube-sr@4.3.11\node_modules\youtube-sr\dist\mod.js:891:13)
    at YouTube.<anonymous> (C:\Users\yerba\Documents\code\youtube_sr_test\node_modules\.pnpm\youtube-sr@4.3.11\node_modules\youtube-sr\dist\mod.js:1281:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\yerba\Documents\code\youtube_sr_test\node_modules\.pnpm\youtube-sr@4.3.11\node_modules\youtube-sr\dist\mod.js:44:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
I tried "retrying" the call if it fails, with 3 seconds of sleep between the calls, but I'm still getting errors. What should I do? Does it have something to do with YT API rate-limiting calls?

**Comment by twlite** [comment]
what's the url?

**Comment by lihuelworks** [comment]
Sorry, here is the expanded info: I'm making a .csv of all info on the videos of my Favorites playlist. For that, I first take all the id's from the videos using .getPlaylist then loop ever the array of ids using .getVideo. I don't know if it's the speed or the ammount of calls that I make (it's a +1k playlist) but I randomly get the error that I mentioned. 

Here is a gist with the code I'm currently using: https://gist.github.com/lihuelworks/05f891acf6b5355824b80144b75f90b0

**Comment by twlite** [comment]
It could be YouTube rate limiting, can you try the lazy method

```js
YouTube.getPlaylist("some_youtube_playlist")
    .then((playlist) => playlist.next()) // fetches next 100 items
    .then(console.log) // all parsable videos
    .catch(console.error);
```

**Comment by twlite** [comment]
With this you can control when to fet h the remaining videos

**Comment by lihuelworks** [comment]
Sorry for the late reply. I've worked a tiny script to get all the IDs of my videos, but I didn't got the real total ammount, it was off by about 150 videos:

![image](https://github.com/twlite/youtube-sr/assets/49965980/f5c30462-3d2d-4add-ba5f-75ba90e6b55e)

![image](https://github.com/twlite/youtube-sr/assets/49965980/cdfec5d2-3fe1-466a-bde8-96fe7a132826)


Here is the code I've used: https://gist.github.com/lihuelworks/04a7d8503b89e51dc3efd771148a07eb

**Comment by lihuelworks** [comment]
Ok, I managed to get the total amount of videos, but I'm still getting random metadata errors.
